-- AlterTable
ALTER TABLE "Anime" ALTER COLUMN "titleJapan" DROP NOT NULL,
ALTER COLUMN "synopsis" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "airedFrom" DROP NOT NULL,
ALTER COLUMN "airedTo" DROP NOT NULL,
ALTER COLUMN "imageURL" DROP NOT NULL,
ALTER COLUMN "episodesCount" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "CastMember" ALTER COLUMN "actorImgURL" DROP NOT NULL,
ALTER COLUMN "characterImgURL" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Episode" ALTER COLUMN "titleJapan" DROP NOT NULL,
ALTER COLUMN "aired" DROP NOT NULL,
ALTER COLUMN "score" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Review" ALTER COLUMN "review" DROP NOT NULL;

-- AlterTable
ALTER TABLE "StaffMember" ALTER COLUMN "imgURL" DROP NOT NULL;

-- AlterTable
ALTER TABLE "StaffOnAnime" ALTER COLUMN "position" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "avatarURL" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL;
